export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const STOP_API_CALL = "STOP_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "USERS_LOGOUT_SUCCESS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
